cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'

# Formulas
brew 'chruby'
brew 'flow'
brew 'git'
brew 'mackup'
brew 'mpv', args: ['with-bundle', 'with-libbluray']
brew 'nvm'
brew 'openssl'
brew 'puma/puma/puma-dev'
brew 'ruby-install'
brew 'z'
brew 'zsh'

# Applications
cask 'alfred'
cask 'appcleaner'
cask 'atom'
cask 'bartender'
cask 'beardedspice'
cask 'caprine'
cask 'controlplane'
cask 'daisydisk'
cask 'dropbox'
cask 'flux'
cask 'github-desktop'
cask 'go2shell'
cask 'google-chrome'
cask 'hazel'
cask 'imageoptim'
cask 'iterm2'
cask 'kodi'
cask 'little-snitch'
cask 'musicbrainz-picard'
cask 'openemu'
cask 'openpht'
cask 'paw'
cask 'postgres'
cask 'postico'
cask 'scroll-reverser'
cask 'selfcontrol'
cask 'torbrowser'
cask 'transmission'
cask 'viscosity'
cask 'xld'

# QuickLook plugins
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'qlvideo'
cask 'quicklook-json'
cask 'betterzipql'
