# Theme - look in ~/.oh-my-zsh/themes/
ZSH_THEME="denkristoffer"

# Plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git nvm yarn history-substring-search)

# oh-my-zsh
. $HOME/.oh-my-zsh/oh-my-zsh.sh

# Load z
. `brew --prefix`/etc/profile.d/z.sh
