# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
# $ZSH/themes/ and $ZSH/plugins/
ZSH_THEME="denkristoffer"
plugins=(git yarn history-substring-search rust thefuck)

export ZSH_COMPDUMP="${ZSH_CACHE_DIR}/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"

. $ZSH/oh-my-zsh.sh

# Load z
. `brew --prefix`/etc/profile.d/z.sh

# fnm
eval "$(fnm env)"

# thefuck
eval $(thefuck --alias fuck)

# Contentful k8s
export KUBECONFIG=~/.kube/cf-authinfo.yaml:~/.kube/cf-staging.yaml:~/.kube/cf-preview.yaml:~/.kube/cf-tools.yaml:~/.kube/cf-production.yaml:~/.kube/cf-auth-okta.yaml
# rust
. "$HOME/.cargo/env"
