# oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
# $ZSH/themes/ and $ZSH/plugins/
ZSH_THEME="denkristoffer"
plugins=(git nvm yarn history-substring-search)

. $ZSH/oh-my-zsh.sh

# Load z
. `brew --prefix`/etc/profile.d/z.sh
